language: node_js
node_js:
  - "13"
  - "12"
  - "10"
  - "8"
install:
  - npm install -g codecov
before_script:
  - npm update -g npm
after_success:
  - codecov --file coverage/lcov.info --disable search